name: run_as_root Quality Gate 🤓
on: [push]
jobs:
  unit-tests:
    name: "Unit Tests 🎉"
    runs-on: ubuntu-latest
    container:
      image: 'registry.gitlab.com/run_as_root/quality_as_root/pipeline/magento2-community:2.3.4-php73'
      credentials:
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_PASSWORD }}
    steps:
      - name: Composer Cache
        uses: actions/cache@v2
        with:
          path: ~/.composer
          key: v1-composer-deps-${{ hashFiles('**/composer-lock.json') }}
          restore-keys: v1-composer-deps-
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Composer
        run: |
             - composer install --prefer-dist --working-dir=/application/build/tools
             - composer --working-dir="/application" config minimum-stability dev
             - composer --working-dir="/application" config prefer-stable true
             - composer --working-dir="/application" require "run-as-root/magento2-prometheus-exporter":"github.ref"
             - composer --working-dir="/application" dump-autoload
             - mkdir -p /application/reports/phpunit/
             - php /application/vendor/bin/phpunit -c phpunit.xml --debug --log-junit /application/reports/phpunit/junit.xml --coverage-clover /application/reports/phpunit/clover.xml --coverage-html /application/reports/phpunit/coverage-html --coverage-text --colors=never

      - name: Run Unit Tests
        run: docker-php-ext-enable xdebug


  codestyle:
    name: "Code Style 🤡"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Composer
        uses: php-actions/composer@v5
      - name: Install PHP CS
        run: composer install --prefer-dist --working-dir=build/tools
      - name: Run PHP Code Style
        run: build/tools/vendor/bin/phpcs --standard=phpcs-ruleset.xml src/ --ignore-annotations